// Code generated by MockGen. DO NOT EDIT.
// Source: src/api//services/ncn.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockNcnService is a mock of NcnService interface.
type MockNcnService struct {
	ctrl     *gomock.Controller
	recorder *MockNcnServiceMockRecorder
}

// MockNcnServiceMockRecorder is the mock recorder for MockNcnService.
type MockNcnServiceMockRecorder struct {
	mock *MockNcnService
}

// NewMockNcnService creates a new mock instance.
func NewMockNcnService(ctrl *gomock.Controller) *MockNcnService {
	mock := &MockNcnService{ctrl: ctrl}
	mock.recorder = &MockNcnServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNcnService) EXPECT() *MockNcnServiceMockRecorder {
	return m.recorder
}
