#
# MIT License
#
# (C) Copyright [2022] Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
global:
  appVersion: 0.0.1

externalHostname: argo.local

cray-service:
  type: "Deployment"
  nameOverride: "cray-nls"
  fullnameOverride: "cray-nls"
  priorityClassName: csm-high-priority-service
  replicaCount: 3
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - cray-nls
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
    type: RollingUpdate
  etcdCluster:
    enabled: false
    tls:
      enabled: false
  initContainers:
    wait-for-argo-server:
      name: "wait-for-argo-server"
      image: 
        repository: artifactory.algol60.net/csm-docker/stable/docker.io/curlimages/curl
        tag: 7.80.0
      pullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -c
        - while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://argo-server-internal.argo.svc.cluster.local:2746)" != "200" ]]; do echo "Waiting for argo server"; sleep 3;  done; echo "Argo Server is UP";

  containers:
    cray-nls:
      name: "cray-nls"
      image:
        repository: artifactory.algol60.net/csm-docker/stable/cray-nls
        tag: 0.0.6
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 256Mi
      env:
        - name: ARGO_TOKEN
          valueFrom:
              secretKeyRef:
                name: argo-server-secret
                key: token
        - name: SERVER_PORT
          value: "3000"
        - name: ENV
          value: production
        - name: GIN_MODE
          value: release
        - name: ARGO_SERVER_URL
          value: argo-server-internal.argo.svc.cluster.local:2746
      ports:
        - name: http
          containerPort: 3000
      livenessProbe:
        httpGet:
          port: 3000
          path: /apis/nls/v1/liveness
        initialDelaySeconds: 5
        periodSeconds: 3
      readinessProbe:
        httpGet:
          port: 3000
          path: /apis/nls/v1/readiness
        initialDelaySeconds: 20
        periodSeconds: 60
  sqlCluster:
    enabled: false
  ingress:
    enabled: true
    prefix: /apis/bss

cray-service-pg-only:
  type: ""
  nameOverride: "cray-nls"
  service:
    enabled: false
  etcdCluster:
    enabled: false
    tls:
      enabled: false
  sqlCluster:
    enabled: true
    tls:
      enabled: false
    waitForItJob: false
    users:
      argouser: []
    databases:
      argo: argouser
    backup:
      enabled: true
      schedule: "10 23 * * *" # Once per day at 11:10 pm

# argo workflow
argo-workflows:
  workflow:
    workflowNamespaces:
      - argo
  server:
    replicas: 3
    image:
      tag: v3.3.6
    pdb:
      enabled: true
      minAvailable: 1
    extraArgs:
      - --auth-mode=server
      - --namespaced
  controller:
    image:
      # -- Registry to use for the controller
      registry: quay.io
      # -- Registry to use for the controller
      repository: argoproj/workflow-controller
      # -- Overrides the image tag whose default is the chart appVersion.
      tag: v3.3.6
    replicas: 2
    pdb:
      enabled: true
      minAvailable: 1
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: Exists
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - argo-workflows-workflow-controller
    persistence:
      postgresql:
        host: cray-nls-postgres
        port: 5432
        database: argo
        tableName: argo_workflows
        # the database secrets must be in the same namespace of the controller
        userNameSecret:
          name: argouser.cray-nls-postgres.credentials
          key: username
        passwordSecret:
          name: argouser.cray-nls-postgres.credentials
          key: password
