#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
basePath: /apis
definitions:
  IufActivity:
    properties:
      spec:
        $ref: '#/definitions/IufActivity.Spec'
    type: object
  IufActivity.Spec:
    properties:
      bootprep_config_managed:
        items:
          type: string
        type: array
      bootprep_config_management:
        items:
          type: string
        type: array
      current_comment:
        type: string
      is_blocked:
        type: boolean
      is_completed:
        type: boolean
      limit_nodes:
        items:
          type: string
        type: array
      media_dir:
        description: location of media
        type: string
      site_parameters:
        description: json string
        type: string
    required:
    - bootprep_config_managed
    - bootprep_config_management
    - media_dir
    - site_parameters
    type: object
info:
  contact: {}
paths:
  /iuf/v1/activities:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/IufActivity'
            type: array
        "501":
          description: Not Implemented
      summary: List IUF activities
      tags:
      - IUF
  /iuf/v1/activities/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: activity id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/IufActivity'
        "501":
          description: Not Implemented
      summary: Get an IUF activity
      tags:
      - IUF
    patch:
      consumes:
      - application/json
      parameters:
      - description: activity id
        in: path
        name: id
        required: true
        type: string
      - description: partial IUF activity
        in: body
        name: partial_activity
        required: true
        schema:
          $ref: '#/definitions/IufActivity'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/IufActivity'
        "501":
          description: Not Implemented
      summary: Patch an IUF activity
      tags:
      - IUF
  /iuf/v1/activity:
    post:
      consumes:
      - application/json
      parameters:
      - description: IUF activity
        in: body
        name: activity
        required: true
        schema:
          $ref: '#/definitions/IufActivity'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/IufActivity'
        "501":
          description: Not Implemented
      summary: Create an IUF activity
      tags:
      - IUF
swagger: "2.0"
