/*
 *
 *  MIT License
 *
 *  (C) Copyright 2022 Hewlett Packard Enterprise Development LP
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a
 *  copy of this software and associated documentation files (the "Software"),
 *  to deal in the Software without restriction, including without limitation
 *  the rights to use, copy, modify, merge, publish, distribute, sublicense,
 *  and/or sell copies of the Software, and to permit persons to whom the
 *  Software is furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included
 *  in all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 *  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 *  OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 *  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 *  OTHER DEALINGS IN THE SOFTWARE.
 *
 */
// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplateIUF = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/iuf/v1/activities": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IUF"
                ],
                "summary": "List IUF activities",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/IufActivity"
                            }
                        }
                    },
                    "501": {
                        "description": "Not Implemented"
                    }
                }
            }
        },
        "/iuf/v1/activities/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IUF"
                ],
                "summary": "Get an IUF activity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "activity id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/IufActivity"
                        }
                    },
                    "501": {
                        "description": "Not Implemented"
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IUF"
                ],
                "summary": "Patch an IUF activity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "activity id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "partial IUF activity",
                        "name": "partial_activity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/IufActivity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/IufActivity"
                        }
                    },
                    "501": {
                        "description": "Not Implemented"
                    }
                }
            }
        },
        "/iuf/v1/activity": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IUF"
                ],
                "summary": "Create an IUF activity",
                "parameters": [
                    {
                        "description": "IUF activity",
                        "name": "activity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/IufActivity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/IufActivity"
                        }
                    },
                    "501": {
                        "description": "Not Implemented"
                    }
                }
            }
        }
    },
    "definitions": {
        "IufActivity": {
            "type": "object",
            "properties": {
                "spec": {
                    "$ref": "#/definitions/IufActivity.Spec"
                }
            }
        },
        "IufActivity.Spec": {
            "type": "object",
            "required": [
                "bootprep_config_managed",
                "bootprep_config_management",
                "media_dir",
                "site_parameters"
            ],
            "properties": {
                "bootprep_config_managed": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "bootprep_config_management": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "current_comment": {
                    "type": "string"
                },
                "is_blocked": {
                    "type": "boolean"
                },
                "limit_nodes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "media_dir": {
                    "description": "location of media",
                    "type": "string"
                },
                "site_parameters": {
                    "description": "json string",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfoIUF holds exported Swagger Info so clients can modify it
var SwaggerInfoIUF = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/apis",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "IUF",
	SwaggerTemplate:  docTemplateIUF,
}

func init() {
	swag.Register(SwaggerInfoIUF.InstanceName(), SwaggerInfoIUF)
}
