#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
basePath: /apis
definitions:
  Activity:
    properties:
      spec:
        $ref: '#/definitions/Activity.Spec'
      status:
        $ref: '#/definitions/Activity.Status'
    type: object
  Activity.Spec:
    properties:
      bootprep_config_managed:
        items:
          type: string
        type: array
      bootprep_config_management:
        items:
          type: string
        type: array
      current_comment:
        type: string
      is_blocked:
        type: boolean
      is_completed:
        type: boolean
      limit_nodes:
        items:
          type: string
        type: array
      media_dir:
        description: location of media
        type: string
      site_parameters:
        description: json string
        type: string
    required:
    - bootprep_config_managed
    - bootprep_config_management
    - media_dir
    - site_parameters
    type: object
  Activity.Status:
    properties:
      bootprep_config_managed:
        items:
          type: string
        type: array
      bootprep_config_management:
        items:
          type: string
        type: array
      limit_nodes:
        items:
          type: string
        type: array
      media_dir:
        description: location of media
        type: string
      products:
        items:
          $ref: '#/definitions/Product'
        type: array
      sessions:
        items:
          $ref: '#/definitions/Session'
        type: array
      site_parameters:
        description: json string
        type: string
    required:
    - bootprep_config_managed
    - bootprep_config_management
    - media_dir
    - site_parameters
    type: object
  Product:
    properties:
      name:
        description: The name of the product
        type: string
      original_location:
        description: The original location of the extracted tar in on the physical
          storage.
        type: string
      version:
        description: The version of the product.
        type: string
    required:
    - name
    - original_location
    - version
    type: object
  Session:
    properties:
      spec:
        $ref: '#/definitions/Session.Spec'
      status:
        $ref: '#/definitions/Session.Status'
    type: object
  Session.CurrentState:
    properties:
      comment:
        type: string
      type:
        type: string
    required:
    - type
    type: object
  Session.Spec:
    properties:
      bootprep_config_managed:
        items:
          type: string
        type: array
      bootprep_config_management:
        items:
          type: string
        type: array
      limit_nodes:
        items:
          type: string
        type: array
      media_dir:
        description: location of media
        type: string
      products:
        items:
          $ref: '#/definitions/Product'
        type: array
      site_parameters:
        description: json string
        type: string
      stages:
        description: |-
          The stages that need to be executed.
          This is either explicitly specified by the Admin, or it is computed from the workflow type.
          An Stage is a group of Operations. Stages represent the overall workflow at a high-level, and executing a stage means executing a bunch of Operations in a predefined manner.  An Admin can specify the stages that must be executed for an install-upgrade workflow. And Product Developers can extend each stage with custom hook scripts that they would like to run before and after the stage's execution.  The high-level stages allow their configuration would revealing too many details to the consumers of IUF.
          if not specified, we apply all stages
        items:
          type: string
        type: array
    required:
    - bootprep_config_managed
    - bootprep_config_management
    - media_dir
    - products
    - site_parameters
    type: object
  Session.Stage:
    properties:
      name:
        type: string
      state:
        type: string
      workflou_id:
        type: string
      workflou_output:
        additionalProperties:
          type: string
        type: object
    required:
    - name
    - state
    - workflou_id
    type: object
  Session.Status:
    properties:
      current_state:
        $ref: '#/definitions/Session.CurrentState'
      stages:
        items:
          $ref: '#/definitions/Session.Stage'
        type: array
    type: object
info:
  contact: {}
paths:
  /iuf/v1/activities:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Activity'
            type: array
        "501":
          description: Not Implemented
      summary: List IUF activities
      tags:
      - Activities
  /iuf/v1/activities/{activity_id}/session:
    post:
      consumes:
      - application/json
      parameters:
      - description: activity id
        in: path
        name: activity_id
        required: true
        type: string
      - description: IUF session
        in: body
        name: session
        required: true
        schema:
          $ref: '#/definitions/Session'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Session'
            type: array
        "501":
          description: Not Implemented
      summary: Create a new session of an IUF activity
      tags:
      - Sessions
  /iuf/v1/activities/{activity_id}/sessions:
    get:
      consumes:
      - application/json
      parameters:
      - description: activity id
        in: path
        name: activity_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Session'
            type: array
        "501":
          description: Not Implemented
      summary: List sessions of an IUF activity
      tags:
      - Sessions
  /iuf/v1/activities/{activity_id}/sessions/{session_id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: activity id
        in: path
        name: activity_id
        required: true
        type: string
      - description: session id
        in: path
        name: session_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Session'
        "501":
          description: Not Implemented
      summary: Stop a running session of an IUF activity
      tags:
      - Sessions
    get:
      consumes:
      - application/json
      parameters:
      - description: activity id
        in: path
        name: activity_id
        required: true
        type: string
      - description: session id
        in: path
        name: session_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Session'
        "501":
          description: Not Implemented
      summary: Get a session of an IUF activity
      tags:
      - Sessions
  /iuf/v1/activities/{activity_id}/sessions/{session_id}/resume:
    post:
      consumes:
      - application/json
      parameters:
      - description: activity id
        in: path
        name: activity_id
        required: true
        type: string
      - description: session id
        in: path
        name: session_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Session'
        "501":
          description: Not Implemented
      summary: Resume a stopped session of an IUF activity
      tags:
      - Sessions
  /iuf/v1/activities/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: activity id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Activity'
        "501":
          description: Not Implemented
      summary: Get an IUF activity
      tags:
      - Activities
    patch:
      consumes:
      - application/json
      parameters:
      - description: activity id
        in: path
        name: id
        required: true
        type: string
      - description: partial IUF activity
        in: body
        name: partial_activity
        required: true
        schema:
          $ref: '#/definitions/Activity'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Activity'
        "501":
          description: Not Implemented
      summary: Patch an IUF activity
      tags:
      - Activities
  /iuf/v1/activity:
    post:
      consumes:
      - application/json
      parameters:
      - description: IUF activity
        in: body
        name: activity
        required: true
        schema:
          $ref: '#/definitions/Activity'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Activity'
        "501":
          description: Not Implemented
      summary: Create an IUF activity
      tags:
      - Activities
swagger: "2.0"
