basePath: /apis/nls
info:
  contact: {}
  description: |
    This doc descibes REST API for ncn lifecycle management. Note that in this version, we only provide APIs for individual operation. A full end to end lifecycle management API is out of scope in Phase I

    ---

    ## Argo workflow Demo

    ---

    [API Doc](swagger.md)
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: NCN Lifecycle Management API
  version: "1.0"
paths:
  /v1/ncns/{hostname}/reboot:
    post:
      consumes:
      - application/json
      parameters:
      - description: hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "501":
          description: Not Implemented
      security:
      - OAuth2Application:
        - admin
      summary: End to end reboot of a single ncn
      tags:
      - NCN
  /v1/ncns/{hostname}/rebuild:
    post:
      consumes:
      - application/json
      parameters:
      - description: hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "501":
          description: Not Implemented
      security:
      - OAuth2Application:
        - admin
      summary: End to end rebuild of a single ncn
      tags:
      - NCN
  /v1/workflows:
    get:
      consumes:
      - application/json
      parameters:
      - collectionFormat: csv
        description: workflow ids
        in: query
        items:
          type: string
        name: workflow_ids
        required: true
        type: array
      produces:
      - application/json
      responses:
        "501":
          description: Not Implemented
      security:
      - OAuth2Application:
        - admin
        - read
      summary: Get status of a ncn workflow
      tags:
      - Workflow
  /v1/workflows/{name}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: name of workflow
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "501":
          description: Not Implemented
      security:
      - OAuth2Application:
        - admin
        - read
      summary: Delete a ncn workflow
      tags:
      - Workflow
  /v1/workflows/{name}/rerun:
    put:
      consumes:
      - application/json
      parameters:
      - description: name of workflow
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "501":
          description: Not Implemented
      security:
      - OAuth2Application:
        - admin
        - read
      summary: Rerun a workflow, all steps will run
      tags:
      - Workflow
  /v1/workflows/{name}/retry:
    put:
      consumes:
      - application/json
      parameters:
      - description: name of workflow
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "501":
          description: Not Implemented
      security:
      - OAuth2Application:
        - admin
        - read
      summary: Retry a failed ncn workflow, skip passed steps
      tags:
      - Workflow
  /v2/ncn:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "501":
          description: Not Implemented
      security:
      - OAuth2Application:
        - admin
      summary: Add a ncn
      tags:
      - NCN v2
  /v2/ncns/{hostname}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "501":
          description: Not Implemented
      security:
      - OAuth2Application:
        - admin
      summary: Remove a ncn
      tags:
      - NCN v2
  /v2/ncns/reboot:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "501":
          description: Not Implemented
      security:
      - OAuth2Application:
        - admin
      summary: End to end rolling reboot request
      tags:
      - NCN v2
  /v2/ncns/rebuild:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "501":
          description: Not Implemented
      security:
      - OAuth2Application:
        - admin
      summary: End to end rolling rebuild request
      tags:
      - NCN v2
securityDefinitions:
  OAuth2Application:
    flow: application
    scopes:
      admin: '                             Grants read and write access to administrative
        information'
      read: '                              Grants read access'
    tokenUrl: https://example.com/oauth/token
    type: oauth2
swagger: "2.0"
