basePath: /api/v1
definitions:
  utils.ResponseError:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: |+
    # (WIP)

    This doc descibes REST API for ncn lifecycle management. Note that in this version, we only provide APIs for individual operation. A full end to end lifecycle management API is out of scope in Phase I


    > TIP: This is Descrption is rendered from `docs/api.md`

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: NCN Lifecycle Management API
  version: "1.0"
paths:
  /etcd/{hostname}/prepare:
    put:
      consumes:
      - application/json
      description: |
        # Prepare baremetal ETCD for rejoining

        Prepare a master ncn to rejoin baremetal etcd cluster

        ## Pre-condition

        1. **NCN** is a **master** node
        1. Baremetal etcd cluster is in **healthy** state
        1. quorum after removal

        ## Action

        1. Remove a ncn from baremetal etcd cluster
        1. Stop etcd services on the ncn
        1. Add the ncn back to etcd cluster so it can rejoin on boot
      parameters:
      - description: Hostname of target ncn
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      summary: Prepare baremetal etcd for a master node to rejoin
      tags:
      - Etcd
  /kubernetes/{hostname}/drain:
    post:
      consumes:
      - application/json
      description: |
        # Drain Kubernetes Node

        Before we can safely drain/remove a node from k8s cluster, we need to run some `CSM specific logic` to make sure a node can be drained from k8s cluster safely

        ---

        ## Master

        #### Pre-condition

        1. **NCN** is a **master** node
        1. quorum after removal

        #### Actions

        1. drain node

        ---

        ## Worker

        #### Pre-condition

        #### Actions
      parameters:
      - description: Hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      summary: Drain a Kubernetes node
      tags:
      - Kubernetes
  /kubernetes/{hostname}/move-first-master:
    post:
      consumes:
      - application/json
      description: |-
        # Move First Master

        We need to make sure first master is not the node being rebuit. We need to move `first_master` to a different master node

        ### Pre-condition

        1. **NCN** is a **master** node
        1. **NCN** is already the **first master**

        ### Action

        1. Loop through other master nodes until `scripts/k8s/promote-initial-master.sh` returns 0
        2. Update `meta-data.first-master-hostname`
      parameters:
      - description: Hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      summary: Move first master from a master k8s node
      tags:
      - Kubernetes
  /kubernetes/{hostname}/post-rebuild:
    post:
      consumes:
      - application/json
      description: |
        # Post Rebuild

        After a node rejoined k8s cluster after rebuild, certain `CSM specific steps` are required. We need to perform such action so we put a system back up health state.

        ---

        ## Master

        #### Pre-condition

        1. **NCN** is a **master** node

        #### Actions

        1. `scripts/k8s/update_kubeapi_istio_ca.sh`

        ---

        ## Worker

        #### Pre-condition

        #### Actions
      parameters:
      - description: Hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      summary: Kubernetes node post rebuild action
      tags:
      - Kubernetes
  /ncn/{hostname}/backup:
    post:
      consumes:
      - application/json
      description: |
        # NCN

        `TODO`

        ---

        ## Master

        #### Pre-condition

        #### Actions

        ---

        ## Worker

        #### Pre-condition

        #### Actions

        ---

        ## Storage

        #### Pre-condition

        #### Actions
      parameters:
      - description: Hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      summary: Create a NCN backup
      tags:
      - NCN
  /ncn/{hostname}/post-rebuild:
    post:
      consumes:
      - application/json
      description: |
        # NCN

        `TODO`

        ---

        ## Master

        #### Pre-condition

        #### Actions

        ---

        ## Worker

        #### Pre-condition

        #### Actions

        ---

        ## Storage

        #### Pre-condition

        #### Actions
      parameters:
      - description: Hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      summary: Perform post rebuild action on a NCN
      tags:
      - NCN
  /ncn/{hostname}/reboot:
    post:
      consumes:
      - application/json
      description: |
        # NCN

        `TODO`

        ---

        ## Master

        #### Pre-condition

        #### Actions

        ---

        ## Worker

        #### Pre-condition

        #### Actions

        ---

        ## Storage

        #### Pre-condition

        #### Actions
      parameters:
      - description: Hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      summary: Perform reboot on a NCN
      tags:
      - NCN
  /ncn/{hostname}/restore:
    post:
      consumes:
      - application/json
      description: |
        # NCN

        `TODO`

        ---

        ## Master

        #### Pre-condition

        #### Actions

        ---

        ## Worker

        #### Pre-condition

        #### Actions

        ---

        ## Storage

        #### Pre-condition

        #### Actions
      parameters:
      - description: Hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      summary: Restore a NCN backup
      tags:
      - NCN
  /ncn/{hostname}/validate:
    post:
      consumes:
      - application/json
      parameters:
      - description: Hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      tags:
      - NCN
  /ncn/{hostname}/wipe:
    post:
      consumes:
      - application/json
      description: |
        # NCN

        `TODO`

        ---

        ## Master

        #### Pre-condition

        #### Actions

        ---

        ## Worker

        #### Pre-condition

        #### Actions

        ---

        ## Storage

        #### Pre-condition

        #### Actions
      parameters:
      - description: Hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      summary: Perform disk wipe on a NCN
      tags:
      - NCN
swagger: "2.0"
