basePath: /api/v1
definitions:
  utils.ResponseError:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: |+
    # (WIP)

    This doc descibes REST API for ncn lifecycle management. Note that in this version, we only provide APIs for individual operation. A full end to end lifecycle management API is out of scope in Phase I


    > TIP: This is Descrption is rendered from `docs/api.md`

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: NCN Lifecycle Management API
  version: "1.0"
paths:
  /etcd/{hostname}/prepare:
    put:
      consumes:
      - application/json
      description: |
        # Prepare baremetal ETCD for rejoining

        Prepare a master ncn to rejoin baremetal etcd cluster

        ## Pre-condition

        1. **NCN** is a **master** node
        1. Baremetal etcd cluster is in **healthy** state
        1. quorum after removal

        ## Action

        1. Remove a ncn from baremetal etcd cluster
        1. Stop etcd services on the ncn
        1. Add the ncn back to etcd cluster so it can rejoin on boot
      parameters:
      - description: Hostname of target ncn
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      summary: Prepare baremetal etcd for a master node to rejoin
      tags:
      - Etcd
  /kubernetes/{hostname}/drain:
    post:
      consumes:
      - application/json
      description: |
        # Drain Kubernetes Node

        Before we can safely drain/remove a node from k8s cluster, we need to run some `CSM specific logic` to make sure a node can be drained from k8s cluster safely

        ---

        ## Master

        #### Pre-condition

        1. **NCN** is a **master** node
        1. quorum after removal

        #### Actions

        1. drain node

        ---

        ## Worker

        #### Pre-condition

        #### Actions
      parameters:
      - description: Hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      summary: Drain a Kubernetes node
      tags:
      - Kubernetes
  /kubernetes/{hostname}/move-first-master:
    post:
      consumes:
      - application/json
      description: |-
        # Move First Master

        We need to make sure first master is not the node being rebuit. We need to move `first_master` to a different master node

        ### Pre-condition

        1. **NCN** is a **master** node
        1. **NCN** is already the **first master**

        ### Action

        1. Loop through other master nodes until `scripts/k8s/promote-initial-master.sh` returns 0
        2. Update `meta-data.first-master-hostname`
      parameters:
      - description: Hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      summary: Move first master from a master k8s node
      tags:
      - Kubernetes
  /kubernetes/{hostname}/post-rebuild:
    post:
      consumes:
      - application/json
      description: |
        # Post Rebuild

        After a node rejoined k8s cluster after rebuild, certain `CSM specific steps` are required. We need to perform such action so we put a system back up health state.

        ---

        ## Master

        #### Pre-condition

        1. **NCN** is a **master** node

        #### Actions

        1. `scripts/k8s/update_kubeapi_istio_ca.sh`

        ---

        ## Worker

        #### Pre-condition

        #### Actions
      parameters:
      - description: Hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      summary: Kubernetes node post rebuild action
      tags:
      - Kubernetes
  /ncn/{hostname}/backup:
    post:
      consumes:
      - application/json
      description: |
        # NCN

        Create backup of a ncn based on a predefined list so critical files can be restored after rebuild.

        ---

        ## Master

        #### Pre-condition

        1. **NCN** is a **master** node

        #### Actions

        1. backup local **sat** file
        1. (m001 only) backup **ifcfg-lan0**
        1. upload backup to s3

        ---

        ## Worker

        #### Pre-condition

        1. **NCN** is a **worker** node

        #### Actions

        ---

        ## Storage

        1. **NCN** is a **ceph storage** node

        #### Pre-condition

        #### Actions
      parameters:
      - description: Hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      summary: Create a NCN backup
      tags:
      - NCN
  /ncn/{hostname}/post-rebuild:
    post:
      consumes:
      - application/json
      description: |
        # NCN

        After a ncn has been rebuilt, some `CSM specific` steps are required.

        ---

        ## Master

        #### Pre-condition

        1. **NCN** is a **master** node

        #### Actions

        1. install latest docs-csm rpm

        ---

        ## Worker

        #### Pre-condition

        #### Actions

        ---

        ## Storage

        #### Pre-condition

        #### Actions
      parameters:
      - description: Hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      summary: Perform post rebuild action on a NCN
      tags:
      - NCN
  /ncn/{hostname}/reboot:
    post:
      consumes:
      - application/json
      description: |
        # NCN

        Set to boot from pxe and power cycle the ncn

        ---

        ## Master/Worker/Storage

        #### Pre-condition

        #### Actions
        1. Set boot to pxe
        2. `ipmitool` power cycle the ncn
      parameters:
      - description: Hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      summary: Perform reboot on a NCN
      tags:
      - NCN
  /ncn/{hostname}/restore:
    post:
      consumes:
      - application/json
      description: |
        # NCN

        Restore previously backup files to a ncn.

        ---

        ## Master/Worker/Storage

        #### Pre-condition

        `N/A`

        #### Actions

        1. download backup from s3
        1. untar/restore backup
      parameters:
      - description: Hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      summary: Restore a NCN backup
      tags:
      - NCN
  /ncn/{hostname}/validate:
    post:
      consumes:
      - application/json
      description: |
        # NCN

        Run validation step of a ncn

        ---

        ## Master/Worker/Storage

        #### Pre-condition

        #### Actions

        1. run goss test
      parameters:
      - description: Hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      summary: Perform validation on a NCN
      tags:
      - NCN
  /ncn/{hostname}/wipe:
    post:
      consumes:
      - application/json
      description: |
        # NCN

        Wipe a ncn's disk and set BSS `metal.no-wipe` to `0` so it actually gets wiped on boot

        ---

        ## Master

        #### Pre-condition

        1. **NCN** is a **master** node

        #### Actions

        1. Wipe disk

        ```
        usb_device_path=$(lsblk -b -l -o TRAN,PATH | awk /usb/'{print $2}')
        usb_rc=$?
        set -e
        if [[ "$usb_rc" -eq 0 ]]; then
            if blkid -p $usb_device_path; then
            have_mnt=0
            for mnt_point in /mnt/rootfs /mnt/sqfs /mnt/livecd /mnt/pitdata; do
                if mountpoint $mnt_point; then
                have_mnt=1
                umount $mnt_point
                fi
            done
            if [ "$have_mnt" -eq 1 ]; then
                eject $usb_device_path
            fi
            fi
        fi
        umount /var/lib/etcd /var/lib/sdu || true
        for md in /dev/md/*; do mdadm -S $md || echo nope ; done
        vgremove -f --select 'vg_name=~metal*' || true
        pvremove /dev/md124 || true
        # Select the devices we care about; RAID, SATA, and NVME devices/handles (but *NOT* USB)
        disk_list=$(lsblk -l -o SIZE,NAME,TYPE,TRAN | grep -E '(raid|sata|nvme|sas)' | sort -u | awk '{print "/dev/"$2}' | tr '\n' ' ')
        for disk in $disk_list; do
            wipefs --all --force wipefs --all --force "$disk" || true
            sgdisk --zap-all "$disk"
        done
        ```

        2. set `metal.no-wipe=0`

        ---

        ## Worker

        1. **NCN** is a **worker** node

        #### Actions

        1. Wipe disk

        ```
        lsblk | grep -q /var/lib/sdu
        sdu_rc=$?
        vgs | grep -q metal
        vgs_rc=$?
        set -e
        systemctl disable kubelet.service || true
        systemctl stop kubelet.service || true
        systemctl disable containerd.service || true
        systemctl stop containerd.service || true
        umount /var/lib/containerd /var/lib/kubelet || true
        if [[ "$sdu_rc" -eq 0 ]]; then
            umount /var/lib/sdu || true
        fi
        for md in /dev/md/*; do mdadm -S $md || echo nope ; done
        if [[ "$vgs_rc" -eq 0 ]]; then
            vgremove -f --select 'vg_name=~metal*' || true
            pvremove /dev/md124 || true
        fi
        wipefs --all --force /dev/sd* /dev/disk/by-label/* || true
        sgdisk --zap-all /dev/sd*
        ```

        2. set `metal.no-wipe=0`

        ---

        ## Storage

        #### Pre-condition

        1. **NCN** is a **storage** node

        #### Actions

        1. Wipe disk

        ```
        for d in $(lsblk | grep -B2 -F md1 | grep ^s | awk '{print $1}'); do wipefs -af "/dev/$d"; done
        ```

        2. set `metal.no-wipe=0`
      parameters:
      - description: Hostname
        in: path
        name: hostname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseError'
      summary: Perform disk wipe on a NCN
      tags:
      - NCN
swagger: "2.0"
