name: Build and Publish Helm charts
on: [push, workflow_dispatch]
jobs:
  build_and_release:
    uses: Cray-HPE/hms-build-chart-workflows/.github/workflows/build_and_release_charts.yaml@v1
    with:
      artifactory-component: cray-nls
      target-branch: master
    secrets:
      jfrog-cli-configuration: ${{ secrets.ARTIFACTORY_ALGOL60_JFROG_CLI_CONFIGURATION }}
